version: '2'

services:
        # The Nextcloud App
        app:  
                build: ./custom_nextcloud
                        
                restart: always
                expose:
                        - "80"
                ports:
                        - 8080:80
                links:
                        - db
                volumes:
                        # Store nextcloud stuff on another drive.
                        # Change /mnt/nextcloud to w/e you want to store nextcloud files.
                        - /mnt/nextcloud:/var/www/html 
                environment:
                        - VIRTUAL_HOST=$NEXTCLOUD_DOMAIN_NAME
                        - LETSENCRYPT_HOST=$NEXTCLOUD_DOMAIN_NAME
                        - LETSENCRYPT_EMAIL=$MY_EMAIL
                          #- LETSENCRYPT_TEST=true
                networks:
                        nextcloud-net:
                                ipv4_address: 10.5.0.5

        # The database for Nextcloud (Mariadb)
        db:
                image: mariadb
                restart: always
                volumes:
                        # Store nextcloud database on another drive.
                        # Change /mn/mariadb to w/e you want to store your database.
                        - /mnt/mariadb:/var/lib/mysql
                networks:
                        nextcloud-net:
                                ipv4_address: 10.5.0.3


        # Nginx reverse proxy so that I can use vhost
        proxy:
                image: jwilder/nginx-proxy
                restart: always
                ports:
                        - 80:80
                        - 443:443
                volumes: 
                        - certs-volume:/etc/nginx/certs
                        - /var/run/docker.sock:/tmp/docker.sock:ro
                        - /etc/nginx/vhost.d:/etc/nginx/vhost.d
                        - /usr/share/nginx/html
                command: "sh -c 'echo \"server_tokens off; client_max_body_size 10G;\" > /etc/nginx/conf.d/my_proxy.conf; forego start -r'"
                networks:
                        nextcloud-net:
                                ipv4_address: 10.5.0.7
                labels:
                        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

        # Let's Encrypt companion for the nginx reverse proxy
        # Shares the ssl cert folder with the reverse proxy
        ssl:
                image: jrcs/letsencrypt-nginx-proxy-companion
                restart: always
                volumes:
                        - certs-volume:/etc/nginx/certs:rw
                        - /var/run/docker.sock:/var/run/docker.sock:ro
                volumes_from:
                        - proxy

volumes:
    # Volume for the ssl certificates that is
    # shared between nginx-proxy and nginx-proxy-companion
    certs-volume:

networks:
        nextcloud-net:
                driver: bridge
                ipam:
                        config:
                                - subnet: 10.5.0.0/16
                                  gateway: 10.5.0.1
